<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Triage Snapshot — {{ $profile }} · TicketLens</title>
    <style>
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; background: #f8f9fa; color: #1a1a2e; min-height: 100vh; }
        .header { background: #1a1a2e; color: #fff; padding: 16px 24px; display: flex; align-items: center; justify-content: space-between; }
        .header h1 { font-size: 1rem; font-weight: 600; letter-spacing: -.01em; }
        .header .meta { font-size: .75rem; color: #94a3b8; }
        .container { max-width: 860px; margin: 32px auto; padding: 0 24px; }
        .ticket { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px 20px; margin-bottom: 12px; }
        .ticket-header { display: flex; align-items: flex-start; gap: 12px; }
        .ticket-key { font-size: .75rem; font-weight: 700; font-family: monospace; background: #f1f5f9; padding: 2px 8px; border-radius: 4px; color: #475569; white-space: nowrap; }
        .ticket-summary { font-size: .9rem; font-weight: 500; line-height: 1.4; flex: 1; }
        .ticket-meta { margin-top: 8px; display: flex; gap: 12px; font-size: .75rem; color: #64748b; flex-wrap: wrap; }
        .badge { padding: 2px 8px; border-radius: 999px; font-size: .7rem; font-weight: 600; display: inline-flex; align-items: center; }
        .badge-needs-response { background: #fef3c7; color: #92400e; }
        .badge-aging { background: #fee2e2; color: #991b1b; }
        .badge-stale { background: #fce7f3; color: #9d174d; }
        .empty { text-align: center; padding: 64px 0; color: #94a3b8; font-size: .9rem; }
        .footer { text-align: center; margin-top: 40px; padding-bottom: 40px; font-size: .75rem; color: #94a3b8; }
        .footer a { color: #6366f1; text-decoration: none; }
    </style>
</head>
<body>
    <div class="header">
        <h1>TicketLens · Triage Snapshot</h1>
        <span class="meta">
            Profile: {{ $profile }}
            · Captured: {{ $capturedAt->format('M j, Y g:i A') }}
            · Expires: {{ $expiresAt->diffForHumans() }}
        </span>
    </div>
    <div class="container">
        @if(count($tickets) === 0)
            <div class="empty">No tickets in this snapshot.</div>
        @else
            @foreach($tickets as $ticket)
                <div class="ticket">
                    <div class="ticket-header">
                        <span class="ticket-key">{{ $ticket['key'] }}</span>
                        <span class="ticket-summary">{{ $ticket['summary'] ?? '(no summary)' }}</span>
                    </div>
                    <div class="ticket-meta">
                        @if(!empty($ticket['status']))
                            <span>{{ $ticket['status'] }}</span>
                        @endif
                        @if(!empty($ticket['assignee']))
                            <span>{{ $ticket['assignee'] }}</span>
                        @endif
                        @foreach($ticket['flags'] ?? [] as $flag)
                            <span class="badge badge-{{ $flag }}">{{ str_replace('-', ' ', $flag) }}</span>
                        @endforeach
                    </div>
                </div>
            @endforeach
        @endif
    </div>
    <div class="footer">
        Generated by <a href="https://ticketlens.io" target="_blank" rel="noopener">TicketLens</a>
        — private by design, zero setup for recipients.
    </div>
</body>
</html>
