<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Adds Owner-issued license support to the licenses table.
 *
 * issued_by_user_id:
 *   NULL = key came from LemonSqueezy webhook (external billing).
 *   NOT NULL = key was generated by an Owner directly from the Console.
 *
 * seats:
 *   Number of members allowed under this license. 1 for Pro/Free, default 5
 *   for Team, 25 for Enterprise. Enforced at service layer during invites.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('licenses', function (Blueprint $table): void {
            $table->foreignId('issued_by_user_id')->nullable()->after('user_id')
                ->constrained('users')->nullOnDelete();
            $table->unsignedSmallInteger('seats')->default(1)->after('tier');
        });
    }

    public function down(): void
    {
        Schema::table('licenses', function (Blueprint $table): void {
            $table->dropConstrainedForeignId('issued_by_user_id');
            $table->dropColumn('seats');
        });
    }
};
